name: akillisehir
description: "A new Flutter project."

# This prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

# Application versioning
version: 1.0.0+1

# Flutter SDK version
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  water_drop_nav_bar: ^2.2.2
  sliding_clipped_nav_bar: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
